### ISSUE TITLE
gsub bad argument

### ISSUE THREAD

**Issue by Zzeyy** [wasabirobby/wasabi_discord#2]
```
[script:wasabi_discor] SCRIPT ERROR: @wasabi_discord/server/server.lua:132: bad argument #1 to 'gsub' (string expected, got nil)
[script:wasabi_discor] > processQueue (@wasabi_discord/server/server.lua:132)
[script:wasabi_discor] > handler (@wasabi_discord/server/server.lua:68)
```

I have not modified the script at all after I set it up, but today it's just not working.

EDIT: Not that it wouldn't work, I'm just getting this error - so something is in deed not working.

**Comment by Zzeyy** [comment]
This basically results in the script telling me I don't have Discord launched,
but that's obviously not true as I always launch both Discord and FiveM at once.

**Comment by wasabirobby** [comment]
Try again with latest
